package team.command;

public enum CommandEnum {
	UNKNOWN_COMMAND, REGISTRATION, CHANGE_BODY,
	TO_PAGE, AUTHORIZATION, EXIT, CHANGE_LANGUAGE,

	SUCCESS, TO_LOG_IN,
	CUSTOMER_MENU, FORM_PROJECT, ADD_PROJECT,
	DEVELOPER_MENU,
	MANAGER_MENU, SHOW_PROJECTS
}
