package team.command;

public enum CommandEnum {
	UNKNOWN_COMMAND, REGISTRATION, CHANGE_BODY, CHANGE_LANGUAGE,
	USER_TAG,

	TO_PAGE, AUTHORIZATION, EXIT, SUCCESS, TO_LOG_IN,
	CUSTOMER_MENU, FORM_PROJECT, ADD_PROJECT, CURRENT_TASK,
	DEVELOPER_MENU,
	MANAGER_MENU, SHOW_PROJECTS, SHOW_TASKS, FREE_DEVELOPERS,
	ASSIGNMENT, ADD_TASK, DELETE_TASK, FORM_TASK
}
